# Generated by Django 2.1.5 on 2020-03-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Number', models.TextField()),
                ('Name', models.TextField()),
                ('Phone', models.TextField()),
                ('Email', models.TextField()),
            ],
        ),
    ]
