# Generated by Django 2.1.5 on 2020-03-11 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Number',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Phone',
        ),
    ]
